services:
  - type: web
    name: painel-ferias
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: FLASK_SECRET_KEY
        value: 29b8b1328e1a24d2aaa86c1dd3cbb2efd4a1f9cfb716a9994cd8a6c87a669246
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        value: |
         {
  "type": "service_account",
  "project_id": "mensagem-automatica-460420",
  "private_key_id": "ed32ca5dced1ff2d649c46bf587d06e902067238",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFOTXkrAK7Py9w\n9NdGDZc5LPUw+z1dc0zjMI5cGKRpbuMAv1lHwJKEY+KOY1iG8r9TLsPGfuujAOPi\nCxCYwIQWspLDL+9HLzXcD4RK8HRXUTQ/xWxeZfD1x2RW5eDDHsox6hCEfdvKrLtO\nCMlLmXc4pJ1VxszLet0gICoQDnfK6+iHGwemfkVgP1lfrdIA7Xo0/hPV4qkgwi6F\n3qaXCPHb4xfO2XwylshqHIaD00TGKVPchujt4N93IzsMhtL6eYKzMBq1AmVlkSmY\nEJEs3G88J1LKMtXwgBaET97MTN/hbQa+ZFlGqYjxo9tE54c7DbRUXS6+O99C2yQk\nc66z+j6XAgMBAAECggEAAzWfoWWFM9ve30U0vaCZ/eWz5cSo5nzqWuYe4vPJtSeH\nTStP/iFtoPbpKG0Ic0W/BFEGAZRuLDxm+PY6Imo7nAzy43dDuxJTG44rFnccRZF+\nOq1xSoX5Kl7AzMM36aT2IGLROv67VWyDLc1pzS+lp4fSQaOXEJaiw5OSa6l4nJY7\n3k50eB3B3lYXBc1XUbVrGECtYC1oKy0R58dx7p+c8okziMkKftK2dRGBVSZVOFrT\ntdltDPDWu6w6DIIY6WBwXOFxkbDAwkGvBprLibIyvXt/K4KZ9UWqtCBVh4vSjjo6\nFLtfd5r8z2Y43DtrGr3MaLWs/pxsEXH6ageUprO0XQKBgQD1tLBtbcvEPutwtKzQ\nHW+6QPMsHlTtTnYmLpuOg/4dB/Gn7eGSz7su+ngG5tqh9/mfdoAKVdj7fBFGkQ/c\niRURicaZHf95SybMBKJsX7AvSSq3wNJblYQxAwrUSHjkoaecJwPP1HK2YPTWgev/\n9fwIii8XdkUNVX2RWVBbvt22cwKBgQDNfIaAKQpcnzzHct4sPknUMgbp6YicHdn+\nxo4s0jipWGh6kEw3q8d9KgprDYJUJeijUEVNpKjLQQz7JZ2/ewecK/qe9llZE/LC\nUosIuBznF4kcaklxJPIPj6mzDM4TexzWBJrwL/mDYUS9XIomYFYqaFgrIqiGWOQl\n70PORNaqTQKBgQDzLNeIFiibm6ItM8PtXZTcg7eoLITlMMhiVbKDRENVvC0BhL/C\nK3IYtq/gNM6hiuk1V3S1xe0wSMRYUO2f2NRPPUqe9D+KbkSBmvydwb5/rixnHKGV\nHs9sKpSnMOrlbNCUDVEKejrmIeNwAbnu5CeC1DBzSgxhfAEAv6J2itqn3QKBgQCH\noEFGJdBpAdEj83Ugzpv8KmjVywYXxLw1pOgCPV6Yp3mOK9+ifwbUXgMyVWBIGh1K\nbZjQfnXKcc0XluRfldyX/48TjJW8baY1DDYoMx0gijA9SQngW/pIuxHO1AzQXtnR\niIibL48IYBL2yTWFzuAQbX6EOgPxaIptX1bpthXZoQKBgGoEem7UGo2fCA68OjAV\nCG4DfvmpXULrlGuLYXjr9EGwtQYdvYCHr8SQ0PGjXK673028lFSHxZOKG2NCRzNR\nNJQqOf15l213Cj7Dt5oYO/28ILXq+CwQKGDXPrSPM4t+IWGTmZOmH90+AETj9+kn\nyV1RXyrT6mfn8wd+6moQ+Ezq\n-----END PRIVATE KEY-----\n",
  "client_email": "mensagem-automatica@mensagem-automatica-460420.iam.gserviceaccount.com",
  "client_id": "102642642308987752860",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mensagem-automatica%40mensagem-automatica-460420.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
      - key: REDIRECT_URI
        value: https://msgferias.onrender.com/callback
