name: Alterar senha automática para início de férias

on:
  schedule:
    - cron: '00 10 * * *' # Roda todo dia às 07h da tarde de Brasília (10h00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  alterar_senha_ferias:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Verificar conteúdo da pasta ferias
        run: ls -la ferias
  
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests google-auth google-api-python-client

      - name: Criar arquivo da Service Account
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > service-account.json

      - name: Acordar backend no Render
        run: |
          curl -s https://msgferias.onrender.com || true
          echo "Aguardando 15 segundos para garantir que o serviço acordou..."
          sleep 15

      - name: Rodar script de alteração de senha
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          AUTH_TOKEN: ${{ secrets.ADMIN_AUTOMATION_TOKEN }}
          FERIAS_SENHA_PADRAO: ${{ secrets.FERIAS_SENHA_PADRAO }}
          SAIDA_SENHA_PADRAO: ${{ secrets.SAIDA_SENHA_PADRAO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON_SCRIPT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_SCRIPT }}
        run: python scripts/alterar_senha_ferias.py
