name: Exclusão automática de contas

on:
  workflow_dispatch:  # ✅ permite execução manual
  schedule:
    - cron: '0 10 * * 1-5'  # Seg a Sex, 07h (Brasília)

jobs:
  excluir-contas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install google-api-python-client google-auth

      - name: Acordar backend no Render
        run: |
          curl -s https://msgferias.onrender.com || true
          echo "Aguardando 15 segundos para garantir que o serviço acordou..."
          sleep 15

      - name: Executar exclusão de contas agendadas
        run: python scripts/excluir_contas.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON_EXCLUSAO: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_EXCLUSAO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
