name: Exclusão automática de contas

on:
  schedule:
    - cron: '0 10 * * 1-5'  # Seg a Sex, 07h da manhã (Brasília, UTC-3)

jobs:
  excluir-contas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: pip install google-api-python-client google-auth
      - name: Executar exclusão de contas agendadas
        run: python scripts/excluir_contas.py
      - name: Executar exclusão de contas agendadas
        run: python scripts/excluir_contas.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON_EXCLUSAO: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_EXCLUSAO }}
